apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-cluster-role
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
      - deployments/scale
      - replicasets
      - replicasets/finalizers
      - replicasets/scale
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
      - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: app-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-cluster-role
